title: Jesus Barrera Mejia
# logo:
description: Hello, my name is Jesus Barrera Mejia. I'm a student at UNCC and am studying acccounting with a minor data science. I am passionate about business, computers, and math. I plan on sitting for my CPA exam in 2025.
theme: jekyll-theme-minimal
